(function(){
  const T=window.TontineModule, esc=MonJeton.escapeHtml; let openId=null;
  const money=n=>new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' FCFA';
  const mine=g=>T.getMyMember(g);
  function groups(){return T.loadTontines().filter(g=>g.type==='avec');}
  function render(){document.getElementById('display-name').textContent=localStorage.getItem('user_name')||'Utilisateur';const list=document.getElementById('avec-list');const data=groups();list.innerHTML=data.length?data.map(g=>{const a=T.ensureAvec(g),me=mine(g),shares=me?T.getMemberShares(g,me.id):0;return `<article class="avec-card"><h3>${esc(g.name)}</h3><p class="muted">Part : ${money(a.shareValue)} · Fonds social : ${money(a.socialFundValue)}</p><p class="amount">Caisse disponible : ${money(T.getAvecFund(g))}</p><p>Votre épargne : ${shares} part(s)</p><button class="btn primary" onclick="window.openAvec('${g.id}')">Ouvrir l’AVEC</button></article>`;}).join(''):'<p class="muted">Aucune AVEC. Créez votre premier groupe.</p>';if(openId) show(openId);}
  function show(id){const g=groups().find(x=>x.id===id);if(!g)return;openId=id;const a=T.ensureAvec(g),me=mine(g),shares=me?T.getMemberShares(g,me.id):0;const loans=a.loans.map(l=>{const m=g.members.find(x=>x.id===l.memberId);return `<div class="activity"><strong>${esc(m?m.name:'Membre')}</strong> — ${money(l.amount)} · ${l.status==='requested'?'à valider':'approuvé'} ${l.purpose?'· '+esc(l.purpose):''}${T.canManageMembers(g)&&l.status==='requested'?`<p><button class="btn primary" onclick="window.approveAvec('${g.id}','${l.id}')">Approuver</button></p>`:''}</div>`}).join('')||'<p class="muted">Aucun prêt demandé.</p>';document.getElementById('modal-content').innerHTML=`<h2>🤝 ${esc(g.name)}</h2><p><strong>Votre épargne :</strong> ${shares} part(s) — ${money(shares*a.shareValue)}</p><p><strong>Caisse de prêts :</strong> ${money(T.getAvecFund(g))} · prêt maximal : 3× votre épargne</p><p><button class="btn primary" onclick="window.savePart('${g.id}')">Enregistrer 1 part</button></p><hr><h3>Demander un prêt</h3><form onsubmit="window.askLoan(event,'${g.id}')"><div class="row"><input name="amount" type="number" min="100" required placeholder="Montant"><input name="purpose" maxlength="160" placeholder="Motif"></div><p><button class="btn secondary">Envoyer la demande</button></p></form><h3>Prêts</h3>${loans}<h3>Historique</h3>${T.getCommunity(g).activity.slice(0,8).map(x=>`<div class="activity">${esc(x.message)}</div>`).join('')||'<p class="muted">Aucune action.</p>'}`;document.getElementById('modal').classList.add('active');}
  window.openAvec=id=>show(id);window.closeModal=()=>{openId=null;document.getElementById('modal').classList.remove('active')};window.savePart=id=>{const g=groups().find(x=>x.id===id),me=mine(g);T.addAvecShare(id,me.id,1);render()};window.askLoan=(e,id)=>{e.preventDefault();const g=groups().find(x=>x.id===id),me=mine(g),r=T.requestAvecLoan(id,me.id,e.currentTarget.amount.value,e.currentTarget.purpose.value);if(r.error)return alert(r.error);render()};window.approveAvec=(id,loan)=>{if(!T.approveAvecLoan(id,loan))return alert('Caisse insuffisante ou droit manquant.');render()};
  document.getElementById('avec-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,g=T.createTontine({name:f.name.value.trim(),type:'avec',amount:f.share.value,frequency:'hebdomadaire',startDate:new Date().toISOString().slice(0,10),members:f.members.value,socialFund:f.social.value,serviceRate:f.rate.value,loanMonths:f.months.value});f.reset();render();show(g.id)});render();
})();
